owner: chicio 
repo: chicio.status.github.io

sites:
  - name: fabrizioduroni.it
    url: https://www.fabrizioduroni.it

status-website:
  cname: status.fabrizioduroni.it
  logoUrl: https://raw.githubusercontent.com/chicio/chicio.github.io/master/_images/blog-logo.jpg
  name: Chicio Coding
  introTitle: "Status monitoring for my website 'Chicio Coding' https://www.fabrizioduroni.it/. Created with upptime, an open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from [chicio.status.github.io](chicio.status.github.io).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
