owner: chicio 
repo: chicio.status.github.io

sites:
  - name: fabrizioduroni.it
    url: https://www.fabrizioduroni.it

status-website:
  cname: status.fabrizioduroni.it
  logoUrl: https://raw.githubusercontent.com/chicio/chicio.github.io/master/_images/blog-logo.jpg
  name: Chicio Coding
  introTitle: "Status monitoring 'Chicio Coding' fabrizioduroni.it domain"
  introMessage: This status page uses **real-time** data from [chicio.status.github.io](chicio.status.github.io). It monitors all the domains and subdomains of fabrizioduroni.it.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/chicio/chicio.status.github.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
